// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxBUUdya6Gy3PBdIUU_Y3OAMRw4bbJ4pc',
    appId: '1:518637504108:web:6d4f03e90c1c91ade73a49',
    messagingSenderId: '518637504108',
    projectId: 'staff-salary-management-c3fc7',
    authDomain: 'staff-salary-management-c3fc7.firebaseapp.com',
    storageBucket: 'staff-salary-management-c3fc7.firebasestorage.app',
    measurementId: 'G-48JG0J4BM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkToD5f3D87c8_PIpETSNc5npjNTVvMQs',
    appId: '1:518637504108:android:a99bccabb7042cf4e73a49',
    messagingSenderId: '518637504108',
    projectId: 'staff-salary-management-c3fc7',
    storageBucket: 'staff-salary-management-c3fc7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoeKtiumlYf09L7kMpmaWMoJJMNIksS5s',
    appId: '1:518637504108:ios:2ffdf8d5d62704b7e73a49',
    messagingSenderId: '518637504108',
    projectId: 'staff-salary-management-c3fc7',
    storageBucket: 'staff-salary-management-c3fc7.firebasestorage.app',
    iosClientId: '518637504108-0p9cba96erttm38360ofrgahboqamd1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffSalaryManagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoeKtiumlYf09L7kMpmaWMoJJMNIksS5s',
    appId: '1:518637504108:ios:2ffdf8d5d62704b7e73a49',
    messagingSenderId: '518637504108',
    projectId: 'staff-salary-management-c3fc7',
    storageBucket: 'staff-salary-management-c3fc7.firebasestorage.app',
    iosClientId: '518637504108-0p9cba96erttm38360ofrgahboqamd1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffSalaryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxBUUdya6Gy3PBdIUU_Y3OAMRw4bbJ4pc',
    appId: '1:518637504108:web:282d9861366fc6eae73a49',
    messagingSenderId: '518637504108',
    projectId: 'staff-salary-management-c3fc7',
    authDomain: 'staff-salary-management-c3fc7.firebaseapp.com',
    storageBucket: 'staff-salary-management-c3fc7.firebasestorage.app',
    measurementId: 'G-LV0WNKW5MZ',
  );
}
